name: Build and Test Java Application

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can change this to your desired Java version
        distribution: 'adopt'  # Specify the distribution here, e.g., 'adopt', 'openjdk', etc.

    - name: Build JAR and Run Tests
      run: |
        mvn clean package  # Replace with your Maven goals
      working-directory: ./  # Specify the path to your Java project

    - name: Upload JAR
      uses: actions/upload-artifact@v2
      with:
        name: my-java-app  # Change this to your desired artifact name
        path: ./target/*.jar  # Modify this to match your build output path

    - name: Download JAR Artifact
      uses: actions/download-artifact@v2
      with:
        name: my-java-app  # Change this to match the artifact name used in the previous job
        path: ./downloaded-jar  # Specify the directory to download the JAR file

    - name: Run JAR File
      run: |
        # Navigate to the directory where the JAR file is located
        cd ./downloaded-jar

        ls -l
        
        # Run the JAR file (adjust the JAR file name as needed)
        java -jar Java-CI-CD-Example-0.0.1-SNAPSHOT.jar &
        sleep 10
    
    - name: Test API
      #JAVA-CI-CD.postman_collection
      run: |
       npm install -g newman
       newman run JAVA-CI-CD.postman_collection.json
   

    - name: Save Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Stop Local Server
      run: |
        pkill -f "custom-app.jar" || true  # Kill the server process gracefully if running
