name: Build, Rename, Run, and Test Java Application

on:
  push:
    branches:
      - master  # Change this to your main branch name if different

jobs:
  build_rename_run_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # You can change this to your desired Java version
        distribution: 'adopt'  # Specify the distribution here, e.g., 'adopt', 'openjdk', etc.

    - name: Build JAR
      run: |
        mvn clean package
        # Adjust the Maven goals if necessary

    - name: Rename JAR File
      run: |
        ORIGINAL_JAR_FILE="./target/original-app.jar"
        CUSTOM_JAR_FILE="./target/custom-app.jar"
        
        # Rename the JAR file (adjust the name as needed)
        mv $ORIGINAL_JAR_FILE $CUSTOM_JAR_FILE
        
        # Store the custom JAR file path in an environment variable
        echo "CUSTOM_JAR_PATH=$CUSTOM_JAR_FILE" >> $GITHUB_ENV

    - name: Run Custom JAR
      run: |
        # Retrieve the custom JAR file path from the environment variable
        CUSTOM_JAR_PATH="$CUSTOM_JAR_PATH"
        
        # Run the custom JAR file
        java -jar $CUSTOM_JAR_PATH &
        sleep 10

    - name: Set up jq (JSON processor)
      run: sudo apt-get install -y jq

    - name: Test API
      run: |
        # Replace with your API endpoint URL (localhost:8080 or any other URL)
        API_URL="http://localhost:8080/some-endpoint"
        
        # Replace with the expected JSON response as a string
        EXPECTED_RESPONSE='{"key":"value"}'
        
        # Make the API request and store the response in a variable
        ACTUAL_RESPONSE=$(curl -sS $API_URL)
        
        # Use jq to pretty-print the responses for debugging (optional)
        echo "Expected Response:"
        echo $EXPECTED_RESPONSE | jq .
        
        echo "Actual Response:"
        echo $ACTUAL_RESPONSE | jq .
        
        # Compare the responses using jq and fail if they don't match
        if [ "$EXPECTED_RESPONSE" != "$ACTUAL_RESPONSE" ]; then
          echo "API response does not match the expected input."
          exit 1
        fi

    - name: Save Maven dependencies
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

    - name: Stop Local Server
      run: |
        pkill -f "custom-app.jar" || true  # Kill the server process gracefully if running
